on: push
name: Publish on Netlify

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Publish to Netlify
      uses: netlify/actions/build@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        # Automatically provided by GitHub
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}  # Optional if you already have a site
        NETLIFY_BASE: 'site'                             # Optional, specify base directory if needed
        NETLIFY_CMD: 'npm run build'                     # Build command, adjust as necessary
        NETLIFY_DIR: 'site/_build'                       # Directory to publish after build
